// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ItemTags  string
	Items     string
	ListItems string
	Lists     string
	Tags      string
}{
	ItemTags:  "item_tags",
	Items:     "items",
	ListItems: "list_items",
	Lists:     "lists",
	Tags:      "tags",
}
